Vagrant.configure("2") do |config|
  config.vm.box = "mitchellh/boot2docker"

  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.network "forwarded_port", guest: 2230, host: 2230, id: 'ssh'
  config.vm.network "forwarded_port", guest: 2231, host: 2231, id: 'ssh'
  config.vm.network "forwarded_port", guest: 2232, host: 2232, id: 'ssh'


  config.vm.provider "virtualbox" do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in TinyCore Linux, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
  end

  # config.vm.provider :virtualbox do |vb|
  #   vb.gui = true
  # end

  ["vmware_fusion", "vmware_workstation"].each do |vmware|
    config.vm.provider vmware do |v|
      if v.respond_to?(:functional_hgfs=)
        v.functional_hgfs = false
      end
    end
  end

  # b2d doesn't support NFS
  config.nfs.functional = false
end
